name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Balkan Elite
      run: DOBRO DOSLI NA SERVER!
    - name: Balkan Elite 
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
